### ISSUE TITLE
Segmentation fault after adding URHO3D_ prefix

### ISSUE THREAD

**Issue by ghost** [MonkeyFirst/urho3d-component-tail-generator#3]
With the latest version of Urho3D several defines like OBJECT and HANDLER now have URHO3D_ prefixed to them. After renaming these in TailGenerator.h/cpp I now get a segmentation fault when compiling and running heXon, which uses your awesome Component. The source of the crash seems to be a call to the SourceBatch destructor when resizing the Vector<SourceBatch>.
This could be a problem in Urho3D, but the TailGenerator is the first crash I run into after this change.

**Comment by ghost** [comment]
Getting more strange bugs with the latest Urho3D pull

**Comment by MonkeyFirst** [comment]
Sorry for waiting, I made some fixes maybe they solve your problems with tail gen.
also I have tested this PR and do not see any crashes.

**Comment by ghost** [comment]
At the moment I think the problem is because of contemporary library modification for a multitasking study. I wanted to try Debian anyway, so I'll see if the crashes are gone after a clean install.

Don't worry. You're doing great stuff. :)
Although I would suggest renaming Tails to Segments in several cases for correctness.

**Comment by ghost** [comment]
Fixed somehow. Local problem.
