### ISSUE TITLE
fullPointPath постоянно увеличиваеются

### ISSUE THREAD

**Issue by 1vanK** [MonkeyFirst/urho3d-component-tail-generator#4]
Туда точки добавляются и добавляются, но нигде не удаляются

**Comment by MonkeyFirst** [comment]
точно, форменное безобразие ) что ты предлагаешь?

**Comment by 1vanK** [comment]
удалять лишние точки с начала списка)

**Comment by 1vanK** [comment]
функцией Erase можно удалить диапазон из PodVector
если число точек больше максимальной длины, удаляем точки из начала вектора

**Comment by 1vanK** [comment]
А очереди не реализованы в ухе, было бы идеально
