### ISSUE TITLE
Drawing glitches with latest Urho3D

### ISSUE THREAD

**Issue by ghost** [MonkeyFirst/urho3d-component-tail-generator#5]
Using this component with a fresh fetch causes drawing glitches on my 64-bit Linux machines.
May be due to [this](https://github.com/urho3d/Urho3D/commit/a458d30fd5daae3713d2468b4fd74b93609fd8ef#diff-1552a827e74ead748055c50a0deff50a) commit, which changed the `SetVertexBuffer` function.
I commented out the mask - which is no longer an argument for SetVertexBuffer - to make [heXon](https://github.com/LucKeyProductions/heXon) compile. I tried adding `vertexBuffer_->SetSize(0, SEM_POSITION | SEM_COLOR | SEM_TEXCOORD, true);` instead, but to no avail.
_Removed screenshot_

**Comment by MonkeyFirst** [comment]
Hi! Thank for noting issue. It's looking weird. But since i do not have free time for dig into it now, so i'm do not familiar with new arbitrary vertex declaration things. If I find free time i'll try to looking into this.

**Comment by ghost** [comment]
I'd be happy to know if you are (or anyone else is) able to recreate the issue. Thanks in advance.  
Gladly I just updated the [itch.io](https://luckeyproductions.itch.io/hexon) download before pulling Urho. :)

**Comment by ghost** [comment]
Works again like a charm. Thanks 1vanK! :)
